import { ArrowLeftIcon } from '@heroicons/react/solid'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { Toaster } from 'react-hot-toast'
import Sidebar from '../components/Sidebar'
import Widgets from '../components/Widgets'

export default function PostPage() {
  const router = useRouter()

  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
  
      <main className='md:max-w-3xl lg:max-w-5xl xl:max-w-[1240px] mx-auto grid grid-cols-10'>
        <Sidebar />
      <div className='border-r border-l border-gray-300 col-span-9
                      lg:col-span-5 xl:col-span-5 '>
        <div className='flex items-center gap-x-5 ml-3'>
          <button 
            className='cursor-pointer'
            onClick={() => router.push('/')}
          >
            <ArrowLeftIcon className='h-5 w-5'/>
          </button>
          <h1 className='font-bold text-lg lg:text-xl sticky top-0 
                        py-3 pl-2 bg-white z-50 cursor-pointer'>
            Tweet
          </h1>
        </div>

        <p className='text-center'>
          This is a Tweet page, which does not exist.
        </p>
        <p className='text-center'>
          Please go back to Home.
        </p>
      </div>
        <Widgets />
      </main>

      <Toaster />
    </div>
  )
}
