import Head from 'next/head'
import { Toaster } from 'react-hot-toast'
import Feed from '../components/Feed'
import Sidebar from '../components/Sidebar'
import Widgets from '../components/Widgets'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
  
      <main className='md:max-w-3xl lg:max-w-5xl xl:max-w-[1240px] mx-auto grid grid-cols-10'>
        <Sidebar />
        <Feed />
        <Widgets />
      </main>

      <Toaster />
    </div>
  )
}
